dist: trusty
language: python

notifications:
  email: false
sudo: false

insntall:
- nvm install 0.10
- npm install

jobs:
  include:
    - stage: style
      script: tox -epep8
    - stage: docs
      script: tox -edocs
    - stage: test
      script: tox -epy35
    -
      script: tox -epy27