#!/bin/bash 
SELF_PATH="$(dirname "$(readlink -f "$0")")"; cd $SELF_PATH;
TMPFILE="/tmp/.handler.$(whoami)"
DEBUG=1


_log(){
  which logger &>/dev/null && logger -t hubot -p local3.notice "$*"; return 0
}


check_error(){
  [[ ! X"$(wc -c "$1" | cut -d" " -f1)" = X"0" ]] && {
    echo "please check the logs, the command was unsuccesfull :/"
    cat "$1" | while read line; do _log "$line"; done
  }
}

/usr/bin/php -f ${PWD}/handlers/handler_charge.php "$1" "$2" "$3" "$4"

exit 0
